#include <errno.h>
#include <moonbit_posix_types.h>

// FFI namespace moonbit_posix_

// https://man7.org/linux/man-pages/man3/errno.3.html
errno_t moonbit_posix_get_errno() { return errno; }
void moonbit_posix_set_errno(errno_t e) { errno = e; }

errno_t moonbit_posix_EPERM() { return EPERM; }
errno_t moonbit_posix_ENOENT() { return ENOENT; }
errno_t moonbit_posix_ESRCH() { return ESRCH; }
errno_t moonbit_posix_EINTR() { return EINTR; }
errno_t moonbit_posix_EIO() { return EIO; }
errno_t moonbit_posix_ENXIO() { return ENXIO; }
errno_t moonbit_posix_E2BIG() { return E2BIG; }
errno_t moonbit_posix_ENOEXEC() { return ENOEXEC; }
errno_t moonbit_posix_EBADF() { return EBADF; }
errno_t moonbit_posix_ECHILD() { return ECHILD; }
errno_t moonbit_posix_EAGAIN() { return EAGAIN; }
errno_t moonbit_posix_ENOMEM() { return ENOMEM; }
errno_t moonbit_posix_EACCES() { return EACCES; }
errno_t moonbit_posix_EFAULT() { return EFAULT; }
errno_t moonbit_posix_ENOTBLK() { return ENOTBLK; }
errno_t moonbit_posix_EBUSY() { return EBUSY; }
errno_t moonbit_posix_EEXIST() { return EEXIST; }
errno_t moonbit_posix_EXDEV() { return EXDEV; }
errno_t moonbit_posix_ENODEV() { return ENODEV; }
errno_t moonbit_posix_ENOTDIR() { return ENOTDIR; }
errno_t moonbit_posix_EISDIR() { return EISDIR; }
errno_t moonbit_posix_EINVAL() { return EINVAL; }
errno_t moonbit_posix_ENFILE() { return ENFILE; }
errno_t moonbit_posix_EMFILE() { return EMFILE; }
errno_t moonbit_posix_ENOTTY() { return ENOTTY; }
errno_t moonbit_posix_ETXTBSY() { return ETXTBSY; }
errno_t moonbit_posix_EFBIG() { return EFBIG; }
errno_t moonbit_posix_ENOSPC() { return ENOSPC; }
errno_t moonbit_posix_ESPIPE() { return ESPIPE; }
errno_t moonbit_posix_EROFS() { return EROFS; }
errno_t moonbit_posix_EMLINK() { return EMLINK; }
errno_t moonbit_posix_EPIPE() { return EPIPE; }
errno_t moonbit_posix_EDOM() { return EDOM; }
errno_t moonbit_posix_ERANGE() { return ERANGE; }
errno_t moonbit_posix_EDEADLK() { return EDEADLK; }
errno_t moonbit_posix_ENAMETOOLONG() { return ENAMETOOLONG; }
errno_t moonbit_posix_ENOLCK() { return ENOLCK; }
errno_t moonbit_posix_ENOSYS() { return ENOSYS; }
errno_t moonbit_posix_ENOTEMPTY() { return ENOTEMPTY; }
errno_t moonbit_posix_ELOOP() { return ELOOP; }
errno_t moonbit_posix_EWOULDBLOCK() { return EWOULDBLOCK; }
errno_t moonbit_posix_ENOMSG() { return ENOMSG; }
errno_t moonbit_posix_EIDRM() { return EIDRM; }
errno_t moonbit_posix_ENOSTR() { return ENOSTR; }
errno_t moonbit_posix_ENODATA() { return ENODATA; }
errno_t moonbit_posix_ETIME() { return ETIME; }
errno_t moonbit_posix_ENOSR() { return ENOSR; }
errno_t moonbit_posix_EREMOTE() { return EREMOTE; }
errno_t moonbit_posix_ENOLINK() { return ENOLINK; }
errno_t moonbit_posix_EPROTO() { return EPROTO; }
errno_t moonbit_posix_EMULTIHOP() { return EMULTIHOP; }
errno_t moonbit_posix_EBADMSG() { return EBADMSG; }
errno_t moonbit_posix_EOVERFLOW() { return EOVERFLOW; }
errno_t moonbit_posix_EILSEQ() { return EILSEQ; }
errno_t moonbit_posix_EUSERS() { return EUSERS; }
errno_t moonbit_posix_ENOTSOCK() { return ENOTSOCK; }
errno_t moonbit_posix_EDESTADDRREQ() { return EDESTADDRREQ; }
errno_t moonbit_posix_EMSGSIZE() { return EMSGSIZE; }
errno_t moonbit_posix_EPROTOTYPE() { return EPROTOTYPE; }
errno_t moonbit_posix_ENOPROTOOPT() { return ENOPROTOOPT; }
errno_t moonbit_posix_EPROTONOSUPPORT() { return EPROTONOSUPPORT; }
errno_t moonbit_posix_ESOCKTNOSUPPORT() { return ESOCKTNOSUPPORT; }
errno_t moonbit_posix_EOPNOTSUPP() { return EOPNOTSUPP; }
errno_t moonbit_posix_EPFNOSUPPORT() { return EPFNOSUPPORT; }
errno_t moonbit_posix_EAFNOSUPPORT() { return EAFNOSUPPORT; }
errno_t moonbit_posix_EADDRINUSE() { return EADDRINUSE; }
errno_t moonbit_posix_EADDRNOTAVAIL() { return EADDRNOTAVAIL; }
errno_t moonbit_posix_ENETDOWN() { return ENETDOWN; }
errno_t moonbit_posix_ENETUNREACH() { return ENETUNREACH; }
errno_t moonbit_posix_ENETRESET() { return ENETRESET; }
errno_t moonbit_posix_ECONNABORTED() { return ECONNABORTED; }
errno_t moonbit_posix_ECONNRESET() { return ECONNRESET; }
errno_t moonbit_posix_ENOBUFS() { return ENOBUFS; }
errno_t moonbit_posix_EISCONN() { return EISCONN; }
errno_t moonbit_posix_ENOTCONN() { return ENOTCONN; }
errno_t moonbit_posix_ESHUTDOWN() { return ESHUTDOWN; }
errno_t moonbit_posix_ETOOMANYREFS() { return ETOOMANYREFS; }
errno_t moonbit_posix_ETIMEDOUT() { return ETIMEDOUT; }
errno_t moonbit_posix_ECONNREFUSED() { return ECONNREFUSED; }
errno_t moonbit_posix_EHOSTDOWN() { return EHOSTDOWN; }
errno_t moonbit_posix_EHOSTUNREACH() { return EHOSTUNREACH; }
errno_t moonbit_posix_EALREADY() { return EALREADY; }
errno_t moonbit_posix_EINPROGRESS() { return EINPROGRESS; }
errno_t moonbit_posix_ESTALE() { return ESTALE; }
errno_t moonbit_posix_EDQUOT() { return EDQUOT; }
errno_t moonbit_posix_ECANCELED() { return ECANCELED; }
errno_t moonbit_posix_EOWNERDEAD() { return EOWNERDEAD; }
errno_t moonbit_posix_ENOTRECOVERABLE() { return ENOTRECOVERABLE; }
errno_t moonbit_posix_ENOTSUP() { return ENOTSUP; }

#ifndef __APPLE__
errno_t moonbit_posix_ECHRNG() { return ECHRNG; }
errno_t moonbit_posix_EL2NSYNC() { return EL2NSYNC; }
errno_t moonbit_posix_EL3HLT() { return EL3HLT; }
errno_t moonbit_posix_EL3RST() { return EL3RST; }
errno_t moonbit_posix_ELNRNG() { return ELNRNG; }
errno_t moonbit_posix_EUNATCH() { return EUNATCH; }
errno_t moonbit_posix_ENOCSI() { return ENOCSI; }
errno_t moonbit_posix_EL2HLT() { return EL2HLT; }
errno_t moonbit_posix_EBADE() { return EBADE; }
errno_t moonbit_posix_EBADR() { return EBADR; }
errno_t moonbit_posix_EXFULL() { return EXFULL; }
errno_t moonbit_posix_ENOANO() { return ENOANO; }
errno_t moonbit_posix_EBADRQC() { return EBADRQC; }
errno_t moonbit_posix_EBADSLT() { return EBADSLT; }
errno_t moonbit_posix_EDEADLOCK() { return EDEADLOCK; }
errno_t moonbit_posix_EBFONT() { return EBFONT; }
errno_t moonbit_posix_ENONET() { return ENONET; }
errno_t moonbit_posix_ENOPKG() { return ENOPKG; }
errno_t moonbit_posix_EADV() { return EADV; }
errno_t moonbit_posix_ESRMNT() { return ESRMNT; }
errno_t moonbit_posix_ECOMM() { return ECOMM; }
errno_t moonbit_posix_ENOTUNIQ() { return ENOTUNIQ; }
errno_t moonbit_posix_EBADFD() { return EBADFD; }
errno_t moonbit_posix_EREMCHG() { return EREMCHG; }
errno_t moonbit_posix_ELIBACC() { return ELIBACC; }
errno_t moonbit_posix_ELIBBAD() { return ELIBBAD; }
errno_t moonbit_posix_ELIBSCN() { return ELIBSCN; }
errno_t moonbit_posix_ELIBMAX() { return ELIBMAX; }
errno_t moonbit_posix_ELIBEXEC() { return ELIBEXEC; }
errno_t moonbit_posix_EDOTDOT() { return EDOTDOT; }
errno_t moonbit_posix_ERESTART() { return ERESTART; }
errno_t moonbit_posix_ESTRPIPE() { return ESTRPIPE; }
errno_t moonbit_posix_EUCLEAN() { return EUCLEAN; }
errno_t moonbit_posix_ENOTNAM() { return ENOTNAM; }
errno_t moonbit_posix_ENAVAIL() { return ENAVAIL; }
errno_t moonbit_posix_EISNAM() { return EISNAM; }
errno_t moonbit_posix_EREMOTEIO() { return EREMOTEIO; }
errno_t moonbit_posix_ENOKEY() { return ENOKEY; }
errno_t moonbit_posix_EKEYEXPIRED() { return EKEYEXPIRED; }
errno_t moonbit_posix_EKEYREVOKED() { return EKEYREVOKED; }
errno_t moonbit_posix_EKEYREJECTED() { return EKEYREJECTED; }
errno_t moonbit_posix_ERFKILL() { return ERFKILL; }
errno_t moonbit_posix_EHWPOISON() { return EHWPOISON; }
errno_t moonbit_posix_ENOMEDIUM() { return ENOMEDIUM; }
errno_t moonbit_posix_EMEDIUMTYPE() { return EMEDIUMTYPE; }

#endif