#include <moonbit_posix_types.h>
#include <unistd.h>

// FFI namespace moonbit_posix_

int32_t moonbit_posix__PC_2_SYMLINKS () { return _PC_2_SYMLINKS; }
int32_t moonbit_posix__PC_ALLOC_SIZE_MIN () { return _PC_ALLOC_SIZE_MIN; }
int32_t moonbit_posix__PC_ASYNC_IO () { return _PC_ASYNC_IO; }
int32_t moonbit_posix__PC_CHOWN_RESTRICTED () { return _PC_CHOWN_RESTRICTED; }
int32_t moonbit_posix__PC_FILESIZEBITS () { return _PC_FILESIZEBITS; }
int32_t moonbit_posix__PC_LINK_MAX () { return _PC_LINK_MAX; }
int32_t moonbit_posix__PC_MAX_CANON () { return _PC_MAX_CANON; }
int32_t moonbit_posix__PC_MAX_INPUT () { return _PC_MAX_INPUT; }
int32_t moonbit_posix__PC_NAME_MAX () { return _PC_NAME_MAX; }
int32_t moonbit_posix__PC_NO_TRUNC () { return _PC_NO_TRUNC; }
int32_t moonbit_posix__PC_PATH_MAX () { return _PC_PATH_MAX; }
int32_t moonbit_posix__PC_PIPE_BUF () { return _PC_PIPE_BUF; }
int32_t moonbit_posix__PC_PRIO_IO () { return _PC_PRIO_IO; }
int32_t moonbit_posix__PC_REC_INCR_XFER_SIZE () { return _PC_REC_INCR_XFER_SIZE; }
int32_t moonbit_posix__PC_REC_MAX_XFER_SIZE () { return _PC_REC_MAX_XFER_SIZE; }
int32_t moonbit_posix__PC_REC_MIN_XFER_SIZE () { return _PC_REC_MIN_XFER_SIZE; }
int32_t moonbit_posix__PC_REC_XFER_ALIGN () { return _PC_REC_XFER_ALIGN; }
int32_t moonbit_posix__PC_SYMLINK_MAX () { return _PC_SYMLINK_MAX; }
int32_t moonbit_posix__PC_SYNC_IO () { return _PC_SYNC_IO; }
int32_t moonbit_posix__PC_VDISABLE () { return _PC_VDISABLE; }

int32_t moonbit_posix__SC_2_C_BIND () { return _SC_2_C_BIND; }
int32_t moonbit_posix__SC_2_C_DEV () { return _SC_2_C_DEV; }
int32_t moonbit_posix__SC_2_CHAR_TERM () { return _SC_2_CHAR_TERM; }
int32_t moonbit_posix__SC_2_FORT_DEV () { return _SC_2_FORT_DEV; }
int32_t moonbit_posix__SC_2_FORT_RUN () { return _SC_2_FORT_RUN; }
int32_t moonbit_posix__SC_2_LOCALEDEF () { return _SC_2_LOCALEDEF; }
int32_t moonbit_posix__SC_2_PBS () { return _SC_2_PBS; }
int32_t moonbit_posix__SC_2_PBS_ACCOUNTING () { return _SC_2_PBS_ACCOUNTING; }
int32_t moonbit_posix__SC_2_PBS_CHECKPOINT () { return _SC_2_PBS_CHECKPOINT; }
int32_t moonbit_posix__SC_2_PBS_LOCATE () { return _SC_2_PBS_LOCATE; }
int32_t moonbit_posix__SC_2_PBS_MESSAGE () { return _SC_2_PBS_MESSAGE; }
int32_t moonbit_posix__SC_2_PBS_TRACK () { return _SC_2_PBS_TRACK; }
int32_t moonbit_posix__SC_2_SW_DEV () { return _SC_2_SW_DEV; }
int32_t moonbit_posix__SC_2_UPE () { return _SC_2_UPE; }
int32_t moonbit_posix__SC_2_VERSION () { return _SC_2_VERSION; }
int32_t moonbit_posix__SC_ADVISORY_INFO () { return _SC_ADVISORY_INFO; }
int32_t moonbit_posix__SC_AIO_LISTIO_MAX () { return _SC_AIO_LISTIO_MAX; }
int32_t moonbit_posix__SC_AIO_MAX () { return _SC_AIO_MAX; }
int32_t moonbit_posix__SC_AIO_PRIO_DELTA_MAX () { return _SC_AIO_PRIO_DELTA_MAX; }
int32_t moonbit_posix__SC_ARG_MAX () { return _SC_ARG_MAX; }
int32_t moonbit_posix__SC_ASYNCHRONOUS_IO () { return _SC_ASYNCHRONOUS_IO; }
int32_t moonbit_posix__SC_ATEXIT_MAX () { return _SC_ATEXIT_MAX; }
int32_t moonbit_posix__SC_BARRIERS () { return _SC_BARRIERS; }
int32_t moonbit_posix__SC_BC_BASE_MAX () { return _SC_BC_BASE_MAX; }
int32_t moonbit_posix__SC_BC_DIM_MAX () { return _SC_BC_DIM_MAX; }
int32_t moonbit_posix__SC_BC_SCALE_MAX () { return _SC_BC_SCALE_MAX; }
int32_t moonbit_posix__SC_BC_STRING_MAX () { return _SC_BC_STRING_MAX; }
int32_t moonbit_posix__SC_CHILD_MAX () { return _SC_CHILD_MAX; }
int32_t moonbit_posix__SC_CLK_TCK () { return _SC_CLK_TCK; }
int32_t moonbit_posix__SC_CLOCK_SELECTION () { return _SC_CLOCK_SELECTION; }
int32_t moonbit_posix__SC_COLL_WEIGHTS_MAX () { return _SC_COLL_WEIGHTS_MAX; }
int32_t moonbit_posix__SC_CPUTIME () { return _SC_CPUTIME; }
int32_t moonbit_posix__SC_DELAYTIMER_MAX () { return _SC_DELAYTIMER_MAX; }
int32_t moonbit_posix__SC_EXPR_NEST_MAX () { return _SC_EXPR_NEST_MAX; }
int32_t moonbit_posix__SC_FSYNC () { return _SC_FSYNC; }
int32_t moonbit_posix__SC_GETGR_R_SIZE_MAX () { return _SC_GETGR_R_SIZE_MAX; }
int32_t moonbit_posix__SC_GETPW_R_SIZE_MAX () { return _SC_GETPW_R_SIZE_MAX; }
int32_t moonbit_posix__SC_HOST_NAME_MAX () { return _SC_HOST_NAME_MAX; }
int32_t moonbit_posix__SC_IOV_MAX () { return _SC_IOV_MAX; }
int32_t moonbit_posix__SC_IPV6 () { return _SC_IPV6; }
int32_t moonbit_posix__SC_JOB_CONTROL () { return _SC_JOB_CONTROL; }
int32_t moonbit_posix__SC_LINE_MAX () { return _SC_LINE_MAX; }
int32_t moonbit_posix__SC_LOGIN_NAME_MAX () { return _SC_LOGIN_NAME_MAX; }
int32_t moonbit_posix__SC_MAPPED_FILES () { return _SC_MAPPED_FILES; }
int32_t moonbit_posix__SC_MEMLOCK () { return _SC_MEMLOCK; }
int32_t moonbit_posix__SC_MEMLOCK_RANGE () { return _SC_MEMLOCK_RANGE; }
int32_t moonbit_posix__SC_MEMORY_PROTECTION () { return _SC_MEMORY_PROTECTION; }
int32_t moonbit_posix__SC_MESSAGE_PASSING () { return _SC_MESSAGE_PASSING; }
int32_t moonbit_posix__SC_MONOTONIC_CLOCK () { return _SC_MONOTONIC_CLOCK; }
int32_t moonbit_posix__SC_MQ_OPEN_MAX () { return _SC_MQ_OPEN_MAX; }
int32_t moonbit_posix__SC_MQ_PRIO_MAX () { return _SC_MQ_PRIO_MAX; }
int32_t moonbit_posix__SC_NGROUPS_MAX () { return _SC_NGROUPS_MAX; }
int32_t moonbit_posix__SC_OPEN_MAX () { return _SC_OPEN_MAX; }
int32_t moonbit_posix__SC_PAGE_SIZE () { return _SC_PAGE_SIZE; }
int32_t moonbit_posix__SC_PAGESIZE () { return _SC_PAGESIZE; }
int32_t moonbit_posix__SC_PRIORITIZED_IO () { return _SC_PRIORITIZED_IO; }
int32_t moonbit_posix__SC_PRIORITY_SCHEDULING () { return _SC_PRIORITY_SCHEDULING; }
int32_t moonbit_posix__SC_RAW_SOCKETS () { return _SC_RAW_SOCKETS; }
int32_t moonbit_posix__SC_RE_DUP_MAX () { return _SC_RE_DUP_MAX; }
int32_t moonbit_posix__SC_READER_WRITER_LOCKS () { return _SC_READER_WRITER_LOCKS; }
int32_t moonbit_posix__SC_REALTIME_SIGNALS () { return _SC_REALTIME_SIGNALS; }
int32_t moonbit_posix__SC_REGEXP () { return _SC_REGEXP; }
int32_t moonbit_posix__SC_RTSIG_MAX () { return _SC_RTSIG_MAX; }
int32_t moonbit_posix__SC_SAVED_IDS () { return _SC_SAVED_IDS; }
int32_t moonbit_posix__SC_SEM_NSEMS_MAX () { return _SC_SEM_NSEMS_MAX; }
int32_t moonbit_posix__SC_SEM_VALUE_MAX () { return _SC_SEM_VALUE_MAX; }
int32_t moonbit_posix__SC_SEMAPHORES () { return _SC_SEMAPHORES; }
int32_t moonbit_posix__SC_SHARED_MEMORY_OBJECTS () { return _SC_SHARED_MEMORY_OBJECTS; }
int32_t moonbit_posix__SC_SHELL () { return _SC_SHELL; }
int32_t moonbit_posix__SC_SIGQUEUE_MAX () { return _SC_SIGQUEUE_MAX; }
int32_t moonbit_posix__SC_SPAWN () { return _SC_SPAWN; }
int32_t moonbit_posix__SC_SPIN_LOCKS () { return _SC_SPIN_LOCKS; }
int32_t moonbit_posix__SC_SPORADIC_SERVER () { return _SC_SPORADIC_SERVER; }
int32_t moonbit_posix__SC_SS_REPL_MAX () { return _SC_SS_REPL_MAX; }
int32_t moonbit_posix__SC_STREAM_MAX () { return _SC_STREAM_MAX; }
int32_t moonbit_posix__SC_SYMLOOP_MAX () { return _SC_SYMLOOP_MAX; }
int32_t moonbit_posix__SC_SYNCHRONIZED_IO () { return _SC_SYNCHRONIZED_IO; }
int32_t moonbit_posix__SC_THREAD_ATTR_STACKADDR () { return _SC_THREAD_ATTR_STACKADDR; }
int32_t moonbit_posix__SC_THREAD_ATTR_STACKSIZE () { return _SC_THREAD_ATTR_STACKSIZE; }
int32_t moonbit_posix__SC_THREAD_CPUTIME () { return _SC_THREAD_CPUTIME; }
int32_t moonbit_posix__SC_THREAD_DESTRUCTOR_ITERATIONS () { return _SC_THREAD_DESTRUCTOR_ITERATIONS; }
int32_t moonbit_posix__SC_THREAD_KEYS_MAX () { return _SC_THREAD_KEYS_MAX; }
int32_t moonbit_posix__SC_THREAD_PRIO_INHERIT () { return _SC_THREAD_PRIO_INHERIT; }
int32_t moonbit_posix__SC_THREAD_PRIO_PROTECT () { return _SC_THREAD_PRIO_PROTECT; }
int32_t moonbit_posix__SC_THREAD_PRIORITY_SCHEDULING () { return _SC_THREAD_PRIORITY_SCHEDULING; }
int32_t moonbit_posix__SC_THREAD_PROCESS_SHARED () { return _SC_THREAD_PROCESS_SHARED; }


int32_t moonbit_posix__SC_THREAD_SAFE_FUNCTIONS () { return _SC_THREAD_SAFE_FUNCTIONS; }
int32_t moonbit_posix__SC_THREAD_SPORADIC_SERVER () { return _SC_THREAD_SPORADIC_SERVER; }
int32_t moonbit_posix__SC_THREAD_STACK_MIN () { return _SC_THREAD_STACK_MIN; }
int32_t moonbit_posix__SC_THREAD_THREADS_MAX () { return _SC_THREAD_THREADS_MAX; }
int32_t moonbit_posix__SC_THREADS () { return _SC_THREADS; }
int32_t moonbit_posix__SC_TIMEOUTS () { return _SC_TIMEOUTS; }
int32_t moonbit_posix__SC_TIMER_MAX () { return _SC_TIMER_MAX; }
int32_t moonbit_posix__SC_TIMERS () { return _SC_TIMERS; }
int32_t moonbit_posix__SC_TRACE () { return _SC_TRACE; }
int32_t moonbit_posix__SC_TRACE_EVENT_FILTER () { return _SC_TRACE_EVENT_FILTER; }
int32_t moonbit_posix__SC_TRACE_EVENT_NAME_MAX () { return _SC_TRACE_EVENT_NAME_MAX; }
int32_t moonbit_posix__SC_TRACE_INHERIT () { return _SC_TRACE_INHERIT; }
int32_t moonbit_posix__SC_TRACE_LOG () { return _SC_TRACE_LOG; }
int32_t moonbit_posix__SC_TRACE_NAME_MAX () { return _SC_TRACE_NAME_MAX; }
int32_t moonbit_posix__SC_TRACE_SYS_MAX () { return _SC_TRACE_SYS_MAX; }
int32_t moonbit_posix__SC_TRACE_USER_EVENT_MAX () { return _SC_TRACE_USER_EVENT_MAX; }
int32_t moonbit_posix__SC_TTY_NAME_MAX () { return _SC_TTY_NAME_MAX; }
int32_t moonbit_posix__SC_TYPED_MEMORY_OBJECTS () { return _SC_TYPED_MEMORY_OBJECTS; }
int32_t moonbit_posix__SC_TZNAME_MAX () { return _SC_TZNAME_MAX; }

int32_t moonbit_posix__SC_V6_ILP32_OFF32 () { return _SC_V6_ILP32_OFF32; }
int32_t moonbit_posix__SC_V6_ILP32_OFFBIG () { return _SC_V6_ILP32_OFFBIG; }
int32_t moonbit_posix__SC_V6_LP64_OFF64 () { return _SC_V6_LP64_OFF64; }
int32_t moonbit_posix__SC_V6_LPBIG_OFFBIG () { return _SC_V6_LPBIG_OFFBIG; }
int32_t moonbit_posix__SC_VERSION () { return _SC_VERSION; }
int32_t moonbit_posix__SC_XOPEN_CRYPT () { return _SC_XOPEN_CRYPT; }
int32_t moonbit_posix__SC_XOPEN_ENH_I18N () { return _SC_XOPEN_ENH_I18N; }
int32_t moonbit_posix__SC_XOPEN_REALTIME () { return _SC_XOPEN_REALTIME; }
int32_t moonbit_posix__SC_XOPEN_REALTIME_THREADS () { return _SC_XOPEN_REALTIME_THREADS; }
int32_t moonbit_posix__SC_XOPEN_SHM () { return _SC_XOPEN_SHM; }
int32_t moonbit_posix__SC_XOPEN_STREAMS () { return _SC_XOPEN_STREAMS; }
int32_t moonbit_posix__SC_XOPEN_UNIX () { return _SC_XOPEN_UNIX; }
int32_t moonbit_posix__SC_XOPEN_VERSION () { return _SC_XOPEN_VERSION; }
int32_t moonbit_posix__CS_PATH () { return _CS_PATH; }

int32_t moonbit_posix__CS_POSIX_V6_ILP32_OFF32_CFLAGS () { return _CS_POSIX_V6_ILP32_OFF32_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_ILP32_OFF32_LDFLAGS () { return _CS_POSIX_V6_ILP32_OFF32_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_ILP32_OFF32_LIBS () { return _CS_POSIX_V6_ILP32_OFF32_LIBS; }
int32_t moonbit_posix__CS_POSIX_V6_ILP32_OFFBIG_CFLAGS () { return _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS () { return _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_ILP32_OFFBIG_LIBS () { return _CS_POSIX_V6_ILP32_OFFBIG_LIBS; }
int32_t moonbit_posix__CS_POSIX_V6_LP64_OFF64_CFLAGS () { return _CS_POSIX_V6_LP64_OFF64_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_LP64_OFF64_LDFLAGS () { return _CS_POSIX_V6_LP64_OFF64_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_LP64_OFF64_LIBS () { return _CS_POSIX_V6_LP64_OFF64_LIBS; }
int32_t moonbit_posix__CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS () { return _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS () { return _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V6_LPBIG_OFFBIG_LIBS () { return _CS_POSIX_V6_LPBIG_OFFBIG_LIBS; }
int32_t moonbit_posix__CS_POSIX_V6_WIDTH_RESTRICTED_ENVS () { return _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS; }


#ifndef __APPLE__

int32_t moonbit_posix__SC_THREAD_ROBUST_PRIO_INHERIT () { return _SC_THREAD_ROBUST_PRIO_INHERIT; }
int32_t moonbit_posix__SC_THREAD_ROBUST_PRIO_PROTECT () { return _SC_THREAD_ROBUST_PRIO_PROTECT; }
int32_t moonbit_posix__SC_V7_ILP32_OFF32 () { return _SC_V7_ILP32_OFF32; }
int32_t moonbit_posix__SC_V7_ILP32_OFFBIG () { return _SC_V7_ILP32_OFFBIG; }
int32_t moonbit_posix__SC_V7_LP64_OFF64 () { return _SC_V7_LP64_OFF64; }
int32_t moonbit_posix__SC_V7_LPBIG_OFFBIG () { return _SC_V7_LPBIG_OFFBIG; }

int32_t moonbit_posix__CS_POSIX_V7_ILP32_OFF32_CFLAGS () { return _CS_POSIX_V7_ILP32_OFF32_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_ILP32_OFF32_LDFLAGS () { return _CS_POSIX_V7_ILP32_OFF32_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_ILP32_OFF32_LIBS () { return _CS_POSIX_V7_ILP32_OFF32_LIBS; }
int32_t moonbit_posix__CS_POSIX_V7_ILP32_OFFBIG_CFLAGS () { return _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS () { return _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_ILP32_OFFBIG_LIBS () { return _CS_POSIX_V7_ILP32_OFFBIG_LIBS; }
int32_t moonbit_posix__CS_POSIX_V7_LP64_OFF64_CFLAGS () { return _CS_POSIX_V7_LP64_OFF64_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_LP64_OFF64_LDFLAGS () { return _CS_POSIX_V7_LP64_OFF64_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_LP64_OFF64_LIBS () { return _CS_POSIX_V7_LP64_OFF64_LIBS; }
int32_t moonbit_posix__CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS () { return _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS () { return _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS; }
int32_t moonbit_posix__CS_POSIX_V7_LPBIG_OFFBIG_LIBS () { return _CS_POSIX_V7_LPBIG_OFFBIG_LIBS; }
int32_t moonbit_posix__CS_POSIX_V7_WIDTH_RESTRICTED_ENVS () { return _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS; }
int32_t moonbit_posix__CS_V7_ENV () { return _CS_V7_ENV; }

int32_t moonbit_posix__CS_V6_ENV () { return _CS_V6_ENV; }

#endif