///|
extern "c" fn __PC_2_SYMLINKS() -> Int = "moonbit_posix__PC_2_SYMLINKS"

///|
extern "c" fn __PC_ALLOC_SIZE_MIN() -> Int = "moonbit_posix__PC_ALLOC_SIZE_MIN"

///|
extern "c" fn __PC_ASYNC_IO() -> Int = "moonbit_posix__PC_ASYNC_IO"

///|
extern "c" fn __PC_CHOWN_RESTRICTED() -> Int = "moonbit_posix__PC_CHOWN_RESTRICTED"

///|
extern "c" fn __PC_FILESIZEBITS() -> Int = "moonbit_posix__PC_FILESIZEBITS"

///|
extern "c" fn __PC_LINK_MAX() -> Int = "moonbit_posix__PC_LINK_MAX"

///|
extern "c" fn __PC_MAX_CANON() -> Int = "moonbit_posix__PC_MAX_CANON"

///|
extern "c" fn __PC_MAX_INPUT() -> Int = "moonbit_posix__PC_MAX_INPUT"

///|
extern "c" fn __PC_NAME_MAX() -> Int = "moonbit_posix__PC_NAME_MAX"

///|
extern "c" fn __PC_NO_TRUNC() -> Int = "moonbit_posix__PC_NO_TRUNC"

///|
extern "c" fn __PC_PATH_MAX() -> Int = "moonbit_posix__PC_PATH_MAX"

///|
extern "c" fn __PC_PIPE_BUF() -> Int = "moonbit_posix__PC_PIPE_BUF"

///|
extern "c" fn __PC_PRIO_IO() -> Int = "moonbit_posix__PC_PRIO_IO"

///|
extern "c" fn __PC_REC_INCR_XFER_SIZE() -> Int = "moonbit_posix__PC_REC_INCR_XFER_SIZE"

///|
extern "c" fn __PC_REC_MAX_XFER_SIZE() -> Int = "moonbit_posix__PC_REC_MAX_XFER_SIZE"

///|
extern "c" fn __PC_REC_MIN_XFER_SIZE() -> Int = "moonbit_posix__PC_REC_MIN_XFER_SIZE"

///|
extern "c" fn __PC_REC_XFER_ALIGN() -> Int = "moonbit_posix__PC_REC_XFER_ALIGN"

///|
extern "c" fn __PC_SYMLINK_MAX() -> Int = "moonbit_posix__PC_SYMLINK_MAX"

///|
extern "c" fn __PC_SYNC_IO() -> Int = "moonbit_posix__PC_SYNC_IO"

///|
extern "c" fn __PC_VDISABLE() -> Int = "moonbit_posix__PC_VDISABLE"

///|
extern "c" fn __SC_2_C_BIND() -> Int = "moonbit_posix__SC_2_C_BIND"

///|
extern "c" fn __SC_2_C_DEV() -> Int = "moonbit_posix__SC_2_C_DEV"

///|
extern "c" fn __SC_2_CHAR_TERM() -> Int = "moonbit_posix__SC_2_CHAR_TERM"

///|
extern "c" fn __SC_2_FORT_DEV() -> Int = "moonbit_posix__SC_2_FORT_DEV"

///|
extern "c" fn __SC_2_FORT_RUN() -> Int = "moonbit_posix__SC_2_FORT_RUN"

///|
extern "c" fn __SC_2_LOCALEDEF() -> Int = "moonbit_posix__SC_2_LOCALEDEF"

///|
extern "c" fn __SC_2_PBS() -> Int = "moonbit_posix__SC_2_PBS"

///|
extern "c" fn __SC_2_PBS_ACCOUNTING() -> Int = "moonbit_posix__SC_2_PBS_ACCOUNTING"

///|
extern "c" fn __SC_2_PBS_CHECKPOINT() -> Int = "moonbit_posix__SC_2_PBS_CHECKPOINT"

///|
extern "c" fn __SC_2_PBS_LOCATE() -> Int = "moonbit_posix__SC_2_PBS_LOCATE"

///|
extern "c" fn __SC_2_PBS_MESSAGE() -> Int = "moonbit_posix__SC_2_PBS_MESSAGE"

///|
extern "c" fn __SC_2_PBS_TRACK() -> Int = "moonbit_posix__SC_2_PBS_TRACK"

///|
extern "c" fn __SC_2_SW_DEV() -> Int = "moonbit_posix__SC_2_SW_DEV"

///|
extern "c" fn __SC_2_UPE() -> Int = "moonbit_posix__SC_2_UPE"

///|
extern "c" fn __SC_2_VERSION() -> Int = "moonbit_posix__SC_2_VERSION"

///|
extern "c" fn __SC_ADVISORY_INFO() -> Int = "moonbit_posix__SC_ADVISORY_INFO"

///|
extern "c" fn __SC_AIO_LISTIO_MAX() -> Int = "moonbit_posix__SC_AIO_LISTIO_MAX"

///|
extern "c" fn __SC_AIO_MAX() -> Int = "moonbit_posix__SC_AIO_MAX"

///|
extern "c" fn __SC_AIO_PRIO_DELTA_MAX() -> Int = "moonbit_posix__SC_AIO_PRIO_DELTA_MAX"

///|
extern "c" fn __SC_ARG_MAX() -> Int = "moonbit_posix__SC_ARG_MAX"

///|
extern "c" fn __SC_ASYNCHRONOUS_IO() -> Int = "moonbit_posix__SC_ASYNCHRONOUS_IO"

///|
extern "c" fn __SC_ATEXIT_MAX() -> Int = "moonbit_posix__SC_ATEXIT_MAX"

///|
extern "c" fn __SC_BARRIERS() -> Int = "moonbit_posix__SC_BARRIERS"

///|
extern "c" fn __SC_BC_BASE_MAX() -> Int = "moonbit_posix__SC_BC_BASE_MAX"

///|
extern "c" fn __SC_BC_DIM_MAX() -> Int = "moonbit_posix__SC_BC_DIM_MAX"

///|
extern "c" fn __SC_BC_SCALE_MAX() -> Int = "moonbit_posix__SC_BC_SCALE_MAX"

///|
extern "c" fn __SC_BC_STRING_MAX() -> Int = "moonbit_posix__SC_BC_STRING_MAX"

///|
extern "c" fn __SC_CHILD_MAX() -> Int = "moonbit_posix__SC_CHILD_MAX"

///|
extern "c" fn __SC_CLK_TCK() -> Int = "moonbit_posix__SC_CLK_TCK"

///|
extern "c" fn __SC_CLOCK_SELECTION() -> Int = "moonbit_posix__SC_CLOCK_SELECTION"

///|
extern "c" fn __SC_COLL_WEIGHTS_MAX() -> Int = "moonbit_posix__SC_COLL_WEIGHTS_MAX"

///|
extern "c" fn __SC_CPUTIME() -> Int = "moonbit_posix__SC_CPUTIME"

///|
extern "c" fn __SC_DELAYTIMER_MAX() -> Int = "moonbit_posix__SC_DELAYTIMER_MAX"

///|
extern "c" fn __SC_EXPR_NEST_MAX() -> Int = "moonbit_posix__SC_EXPR_NEST_MAX"

///|
extern "c" fn __SC_FSYNC() -> Int = "moonbit_posix__SC_FSYNC"

///|
extern "c" fn __SC_GETGR_R_SIZE_MAX() -> Int = "moonbit_posix__SC_GETGR_R_SIZE_MAX"

///|
extern "c" fn __SC_GETPW_R_SIZE_MAX() -> Int = "moonbit_posix__SC_GETPW_R_SIZE_MAX"

///|
extern "c" fn __SC_HOST_NAME_MAX() -> Int = "moonbit_posix__SC_HOST_NAME_MAX"

///|
extern "c" fn __SC_IOV_MAX() -> Int = "moonbit_posix__SC_IOV_MAX"

///|
extern "c" fn __SC_IPV6() -> Int = "moonbit_posix__SC_IPV6"

///|
extern "c" fn __SC_JOB_CONTROL() -> Int = "moonbit_posix__SC_JOB_CONTROL"

///|
extern "c" fn __SC_LINE_MAX() -> Int = "moonbit_posix__SC_LINE_MAX"

///|
extern "c" fn __SC_LOGIN_NAME_MAX() -> Int = "moonbit_posix__SC_LOGIN_NAME_MAX"

///|
extern "c" fn __SC_MAPPED_FILES() -> Int = "moonbit_posix__SC_MAPPED_FILES"

///|
extern "c" fn __SC_MEMLOCK() -> Int = "moonbit_posix__SC_MEMLOCK"

///|
extern "c" fn __SC_MEMLOCK_RANGE() -> Int = "moonbit_posix__SC_MEMLOCK_RANGE"

///|
extern "c" fn __SC_MEMORY_PROTECTION() -> Int = "moonbit_posix__SC_MEMORY_PROTECTION"

///|
extern "c" fn __SC_MESSAGE_PASSING() -> Int = "moonbit_posix__SC_MESSAGE_PASSING"

///|
extern "c" fn __SC_MONOTONIC_CLOCK() -> Int = "moonbit_posix__SC_MONOTONIC_CLOCK"

///|
extern "c" fn __SC_MQ_OPEN_MAX() -> Int = "moonbit_posix__SC_MQ_OPEN_MAX"

///|
extern "c" fn __SC_MQ_PRIO_MAX() -> Int = "moonbit_posix__SC_MQ_PRIO_MAX"

///|
extern "c" fn __SC_NGROUPS_MAX() -> Int = "moonbit_posix__SC_NGROUPS_MAX"

///|
extern "c" fn __SC_OPEN_MAX() -> Int = "moonbit_posix__SC_OPEN_MAX"

///|
extern "c" fn __SC_PAGE_SIZE() -> Int = "moonbit_posix__SC_PAGE_SIZE"

///|
extern "c" fn __SC_PAGESIZE() -> Int = "moonbit_posix__SC_PAGESIZE"

///|
extern "c" fn __SC_PRIORITIZED_IO() -> Int = "moonbit_posix__SC_PRIORITIZED_IO"

///|
extern "c" fn __SC_PRIORITY_SCHEDULING() -> Int = "moonbit_posix__SC_PRIORITY_SCHEDULING"

///|
extern "c" fn __SC_RAW_SOCKETS() -> Int = "moonbit_posix__SC_RAW_SOCKETS"

///|
extern "c" fn __SC_RE_DUP_MAX() -> Int = "moonbit_posix__SC_RE_DUP_MAX"

///|
extern "c" fn __SC_READER_WRITER_LOCKS() -> Int = "moonbit_posix__SC_READER_WRITER_LOCKS"

///|
extern "c" fn __SC_REALTIME_SIGNALS() -> Int = "moonbit_posix__SC_REALTIME_SIGNALS"

///|
extern "c" fn __SC_REGEXP() -> Int = "moonbit_posix__SC_REGEXP"

///|
extern "c" fn __SC_RTSIG_MAX() -> Int = "moonbit_posix__SC_RTSIG_MAX"

///|
extern "c" fn __SC_SAVED_IDS() -> Int = "moonbit_posix__SC_SAVED_IDS"

///|
extern "c" fn __SC_SEM_NSEMS_MAX() -> Int = "moonbit_posix__SC_SEM_NSEMS_MAX"

///|
extern "c" fn __SC_SEM_VALUE_MAX() -> Int = "moonbit_posix__SC_SEM_VALUE_MAX"

///|
extern "c" fn __SC_SEMAPHORES() -> Int = "moonbit_posix__SC_SEMAPHORES"

///|
extern "c" fn __SC_SHARED_MEMORY_OBJECTS() -> Int = "moonbit_posix__SC_SHARED_MEMORY_OBJECTS"

///|
extern "c" fn __SC_SHELL() -> Int = "moonbit_posix__SC_SHELL"

///|
extern "c" fn __SC_SIGQUEUE_MAX() -> Int = "moonbit_posix__SC_SIGQUEUE_MAX"

///|
extern "c" fn __SC_SPAWN() -> Int = "moonbit_posix__SC_SPAWN"

///|
extern "c" fn __SC_SPIN_LOCKS() -> Int = "moonbit_posix__SC_SPIN_LOCKS"

///|
extern "c" fn __SC_SPORADIC_SERVER() -> Int = "moonbit_posix__SC_SPORADIC_SERVER"

///|
extern "c" fn __SC_SS_REPL_MAX() -> Int = "moonbit_posix__SC_SS_REPL_MAX"

///|
extern "c" fn __SC_STREAM_MAX() -> Int = "moonbit_posix__SC_STREAM_MAX"

///|
extern "c" fn __SC_SYMLOOP_MAX() -> Int = "moonbit_posix__SC_SYMLOOP_MAX"

///|
extern "c" fn __SC_SYNCHRONIZED_IO() -> Int = "moonbit_posix__SC_SYNCHRONIZED_IO"

///|
extern "c" fn __SC_THREAD_ATTR_STACKADDR() -> Int = "moonbit_posix__SC_THREAD_ATTR_STACKADDR"

///|
extern "c" fn __SC_THREAD_ATTR_STACKSIZE() -> Int = "moonbit_posix__SC_THREAD_ATTR_STACKSIZE"

///|
extern "c" fn __SC_THREAD_CPUTIME() -> Int = "moonbit_posix__SC_THREAD_CPUTIME"

///|
extern "c" fn __SC_THREAD_DESTRUCTOR_ITERATIONS() -> Int = "moonbit_posix__SC_THREAD_DESTRUCTOR_ITERATIONS"

///|
extern "c" fn __SC_THREAD_KEYS_MAX() -> Int = "moonbit_posix__SC_THREAD_KEYS_MAX"

///|
extern "c" fn __SC_THREAD_PRIO_INHERIT() -> Int = "moonbit_posix__SC_THREAD_PRIO_INHERIT"

///|
extern "c" fn __SC_THREAD_PRIO_PROTECT() -> Int = "moonbit_posix__SC_THREAD_PRIO_PROTECT"

///|
extern "c" fn __SC_THREAD_PRIORITY_SCHEDULING() -> Int = "moonbit_posix__SC_THREAD_PRIORITY_SCHEDULING"

///|
extern "c" fn __SC_THREAD_PROCESS_SHARED() -> Int = "moonbit_posix__SC_THREAD_PROCESS_SHARED"

///|
extern "c" fn __SC_THREAD_ROBUST_PRIO_INHERIT() -> Int = "moonbit_posix__SC_THREAD_ROBUST_PRIO_INHERIT"

///|
extern "c" fn __SC_THREAD_ROBUST_PRIO_PROTECT() -> Int = "moonbit_posix__SC_THREAD_ROBUST_PRIO_PROTECT"

///|
extern "c" fn __SC_THREAD_SAFE_FUNCTIONS() -> Int = "moonbit_posix__SC_THREAD_SAFE_FUNCTIONS"

///|
extern "c" fn __SC_THREAD_SPORADIC_SERVER() -> Int = "moonbit_posix__SC_THREAD_SPORADIC_SERVER"

///|
extern "c" fn __SC_THREAD_STACK_MIN() -> Int = "moonbit_posix__SC_THREAD_STACK_MIN"

///|
extern "c" fn __SC_THREAD_THREADS_MAX() -> Int = "moonbit_posix__SC_THREAD_THREADS_MAX"

///|
extern "c" fn __SC_THREADS() -> Int = "moonbit_posix__SC_THREADS"

///|
extern "c" fn __SC_TIMEOUTS() -> Int = "moonbit_posix__SC_TIMEOUTS"

///|
extern "c" fn __SC_TIMER_MAX() -> Int = "moonbit_posix__SC_TIMER_MAX"

///|
extern "c" fn __SC_TIMERS() -> Int = "moonbit_posix__SC_TIMERS"

///|
extern "c" fn __SC_TRACE() -> Int = "moonbit_posix__SC_TRACE"

///|
extern "c" fn __SC_TRACE_EVENT_FILTER() -> Int = "moonbit_posix__SC_TRACE_EVENT_FILTER"

///|
extern "c" fn __SC_TRACE_EVENT_NAME_MAX() -> Int = "moonbit_posix__SC_TRACE_EVENT_NAME_MAX"

///|
extern "c" fn __SC_TRACE_INHERIT() -> Int = "moonbit_posix__SC_TRACE_INHERIT"

///|
extern "c" fn __SC_TRACE_LOG() -> Int = "moonbit_posix__SC_TRACE_LOG"

///|
extern "c" fn __SC_TRACE_NAME_MAX() -> Int = "moonbit_posix__SC_TRACE_NAME_MAX"

///|
extern "c" fn __SC_TRACE_SYS_MAX() -> Int = "moonbit_posix__SC_TRACE_SYS_MAX"

///|
extern "c" fn __SC_TRACE_USER_EVENT_MAX() -> Int = "moonbit_posix__SC_TRACE_USER_EVENT_MAX"

///|
extern "c" fn __SC_TTY_NAME_MAX() -> Int = "moonbit_posix__SC_TTY_NAME_MAX"

///|
extern "c" fn __SC_TYPED_MEMORY_OBJECTS() -> Int = "moonbit_posix__SC_TYPED_MEMORY_OBJECTS"

///|
extern "c" fn __SC_TZNAME_MAX() -> Int = "moonbit_posix__SC_TZNAME_MAX"

///|
extern "c" fn __SC_V7_ILP32_OFF32() -> Int = "moonbit_posix__SC_V7_ILP32_OFF32"

///|
extern "c" fn __SC_V7_ILP32_OFFBIG() -> Int = "moonbit_posix__SC_V7_ILP32_OFFBIG"

///|
extern "c" fn __SC_V7_LP64_OFF64() -> Int = "moonbit_posix__SC_V7_LP64_OFF64"

///|
extern "c" fn __SC_V7_LPBIG_OFFBIG() -> Int = "moonbit_posix__SC_V7_LPBIG_OFFBIG"

///|
extern "c" fn __SC_V6_ILP32_OFF32() -> Int = "moonbit_posix__SC_V6_ILP32_OFF32"

///|
extern "c" fn __SC_V6_ILP32_OFFBIG() -> Int = "moonbit_posix__SC_V6_ILP32_OFFBIG"

///|
extern "c" fn __SC_V6_LP64_OFF64() -> Int = "moonbit_posix__SC_V6_LP64_OFF64"

///|
extern "c" fn __SC_V6_LPBIG_OFFBIG() -> Int = "moonbit_posix__SC_V6_LPBIG_OFFBIG"

///|
extern "c" fn __SC_VERSION() -> Int = "moonbit_posix__SC_VERSION"

///|
extern "c" fn __SC_XOPEN_CRYPT() -> Int = "moonbit_posix__SC_XOPEN_CRYPT"

///|
extern "c" fn __SC_XOPEN_ENH_I18N() -> Int = "moonbit_posix__SC_XOPEN_ENH_I18N"

///|
extern "c" fn __SC_XOPEN_REALTIME() -> Int = "moonbit_posix__SC_XOPEN_REALTIME"

///|
extern "c" fn __SC_XOPEN_REALTIME_THREADS() -> Int = "moonbit_posix__SC_XOPEN_REALTIME_THREADS"

///|
extern "c" fn __SC_XOPEN_SHM() -> Int = "moonbit_posix__SC_XOPEN_SHM"

///|
extern "c" fn __SC_XOPEN_STREAMS() -> Int = "moonbit_posix__SC_XOPEN_STREAMS"

///|
extern "c" fn __SC_XOPEN_UNIX() -> Int = "moonbit_posix__SC_XOPEN_UNIX"

///|
extern "c" fn __SC_XOPEN_VERSION() -> Int = "moonbit_posix__SC_XOPEN_VERSION"

///|
extern "c" fn __CS_PATH() -> Int = "moonbit_posix__CS_PATH"

///|
extern "c" fn __CS_POSIX_V7_ILP32_OFF32_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_ILP32_OFF32_CFLAGS"

///|
extern "c" fn __CS_POSIX_V7_ILP32_OFF32_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_ILP32_OFF32_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V7_ILP32_OFF32_LIBS() -> Int = "moonbit_posix__CS_POSIX_V7_ILP32_OFF32_LIBS"

///|
extern "c" fn __CS_POSIX_V7_ILP32_OFFBIG_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_ILP32_OFFBIG_CFLAGS"

///|
extern "c" fn __CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V7_ILP32_OFFBIG_LIBS() -> Int = "moonbit_posix__CS_POSIX_V7_ILP32_OFFBIG_LIBS"

///|
extern "c" fn __CS_POSIX_V7_LP64_OFF64_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_LP64_OFF64_CFLAGS"

///|
extern "c" fn __CS_POSIX_V7_LP64_OFF64_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_LP64_OFF64_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V7_LP64_OFF64_LIBS() -> Int = "moonbit_posix__CS_POSIX_V7_LP64_OFF64_LIBS"

///|
extern "c" fn __CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS"

///|
extern "c" fn __CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V7_LPBIG_OFFBIG_LIBS() -> Int = "moonbit_posix__CS_POSIX_V7_LPBIG_OFFBIG_LIBS"

///|
extern "c" fn __CS_POSIX_V7_WIDTH_RESTRICTED_ENVS() -> Int = "moonbit_posix__CS_POSIX_V7_WIDTH_RESTRICTED_ENVS"

///|
extern "c" fn __CS_V7_ENV() -> Int = "moonbit_posix__CS_V7_ENV"

///|
extern "c" fn __CS_POSIX_V6_ILP32_OFF32_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_ILP32_OFF32_CFLAGS"

///|
extern "c" fn __CS_POSIX_V6_ILP32_OFF32_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_ILP32_OFF32_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V6_ILP32_OFF32_LIBS() -> Int = "moonbit_posix__CS_POSIX_V6_ILP32_OFF32_LIBS"

///|
extern "c" fn __CS_POSIX_V6_ILP32_OFFBIG_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_ILP32_OFFBIG_CFLAGS"

///|
extern "c" fn __CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V6_ILP32_OFFBIG_LIBS() -> Int = "moonbit_posix__CS_POSIX_V6_ILP32_OFFBIG_LIBS"

///|
extern "c" fn __CS_POSIX_V6_LP64_OFF64_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_LP64_OFF64_CFLAGS"

///|
extern "c" fn __CS_POSIX_V6_LP64_OFF64_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_LP64_OFF64_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V6_LP64_OFF64_LIBS() -> Int = "moonbit_posix__CS_POSIX_V6_LP64_OFF64_LIBS"

///|
extern "c" fn __CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS"

///|
extern "c" fn __CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS() -> Int = "moonbit_posix__CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS"

///|
extern "c" fn __CS_POSIX_V6_LPBIG_OFFBIG_LIBS() -> Int = "moonbit_posix__CS_POSIX_V6_LPBIG_OFFBIG_LIBS"

///|
extern "c" fn __CS_POSIX_V6_WIDTH_RESTRICTED_ENVS() -> Int = "moonbit_posix__CS_POSIX_V6_WIDTH_RESTRICTED_ENVS"

///|
extern "c" fn __CS_V6_ENV() -> Int = "moonbit_posix__CS_V6_ENV"

///|
pub let _pc_2_symlinks : Int = __PC_2_SYMLINKS()

///|
pub let _pc_alloc_size_min : Int = __PC_ALLOC_SIZE_MIN()

///|
pub let _pc_async_io : Int = __PC_ASYNC_IO()

///|
pub let _pc_chown_restricted : Int = __PC_CHOWN_RESTRICTED()

///|
pub let _pc_filesizebits : Int = __PC_FILESIZEBITS()

///|
pub let _pc_link_max : Int = __PC_LINK_MAX()

///|
pub let _pc_max_canon : Int = __PC_MAX_CANON()

///|
pub let _pc_max_input : Int = __PC_MAX_INPUT()

///|
pub let _pc_name_max : Int = __PC_NAME_MAX()

///|
pub let _pc_no_trunc : Int = __PC_NO_TRUNC()

///|
pub let _pc_path_max : Int = __PC_PATH_MAX()

///|
pub let _pc_pipe_buf : Int = __PC_PIPE_BUF()

///|
pub let _pc_prio_io : Int = __PC_PRIO_IO()

///|
pub let _pc_rec_incr_xfer_size : Int = __PC_REC_INCR_XFER_SIZE()

///|
pub let _pc_rec_max_xfer_size : Int = __PC_REC_MAX_XFER_SIZE()

///|
pub let _pc_rec_min_xfer_size : Int = __PC_REC_MIN_XFER_SIZE()

///|
pub let _pc_rec_xfer_align : Int = __PC_REC_XFER_ALIGN()

///|
pub let _pc_symlink_max : Int = __PC_SYMLINK_MAX()

///|
pub let _pc_sync_io : Int = __PC_SYNC_IO()

///|
pub let _pc_vdisable : Int = __PC_VDISABLE()

///|
pub let _sc_2_c_bind : Int = __SC_2_C_BIND()

///|
pub let _sc_2_c_dev : Int = __SC_2_C_DEV()

///|
pub let _sc_2_char_term : Int = __SC_2_CHAR_TERM()

///|
pub let _sc_2_fort_dev : Int = __SC_2_FORT_DEV()

///|
pub let _sc_2_fort_run : Int = __SC_2_FORT_RUN()

///|
pub let _sc_2_localedef : Int = __SC_2_LOCALEDEF()

///|
pub let _sc_2_pbs : Int = __SC_2_PBS()

///|
pub let _sc_2_pbs_accounting : Int = __SC_2_PBS_ACCOUNTING()

///|
pub let _sc_2_pbs_checkpoint : Int = __SC_2_PBS_CHECKPOINT()

///|
pub let _sc_2_pbs_locate : Int = __SC_2_PBS_LOCATE()

///|
pub let _sc_2_pbs_message : Int = __SC_2_PBS_MESSAGE()

///|
pub let _sc_2_pbs_track : Int = __SC_2_PBS_TRACK()

///|
pub let _sc_2_sw_dev : Int = __SC_2_SW_DEV()

///|
pub let _sc_2_upe : Int = __SC_2_UPE()

///|
pub let _sc_2_version : Int = __SC_2_VERSION()

///|
pub let _sc_advisory_info : Int = __SC_ADVISORY_INFO()

///|
pub let _sc_aio_listio_max : Int = __SC_AIO_LISTIO_MAX()

///|
pub let _sc_aio_max : Int = __SC_AIO_MAX()

///|
pub let _sc_aio_prio_delta_max : Int = __SC_AIO_PRIO_DELTA_MAX()

///|
pub let _sc_arg_max : Int = __SC_ARG_MAX()

///|
pub let _sc_asynchronous_io : Int = __SC_ASYNCHRONOUS_IO()

///|
pub let _sc_atexit_max : Int = __SC_ATEXIT_MAX()

///|
pub let _sc_barriers : Int = __SC_BARRIERS()

///|
pub let _sc_bc_base_max : Int = __SC_BC_BASE_MAX()

///|
pub let _sc_bc_dim_max : Int = __SC_BC_DIM_MAX()

///|
pub let _sc_bc_scale_max : Int = __SC_BC_SCALE_MAX()

///|
pub let _sc_bc_string_max : Int = __SC_BC_STRING_MAX()

///|
pub let _sc_child_max : Int = __SC_CHILD_MAX()

///|
pub let _sc_clk_tck : Int = __SC_CLK_TCK()

///|
pub let _sc_clock_selection : Int = __SC_CLOCK_SELECTION()

///|
pub let _sc_coll_weights_max : Int = __SC_COLL_WEIGHTS_MAX()

///|
pub let _sc_cputime : Int = __SC_CPUTIME()

///|
pub let _sc_delaytimer_max : Int = __SC_DELAYTIMER_MAX()

///|
pub let _sc_expr_nest_max : Int = __SC_EXPR_NEST_MAX()

///|
pub let _sc_fsync : Int = __SC_FSYNC()

///|
pub let _sc_getgr_r_size_max : Int = __SC_GETGR_R_SIZE_MAX()

///|
pub let _sc_getpw_r_size_max : Int = __SC_GETPW_R_SIZE_MAX()

///|
pub let _sc_host_name_max : Int = __SC_HOST_NAME_MAX()

///|
pub let _sc_iov_max : Int = __SC_IOV_MAX()

///|
pub let _sc_ipv6 : Int = __SC_IPV6()

///|
pub let _sc_job_control : Int = __SC_JOB_CONTROL()

///|
pub let _sc_line_max : Int = __SC_LINE_MAX()

///|
pub let _sc_login_name_max : Int = __SC_LOGIN_NAME_MAX()

///|
pub let _sc_mapped_files : Int = __SC_MAPPED_FILES()

///|
pub let _sc_memlock : Int = __SC_MEMLOCK()

///|
pub let _sc_memlock_range : Int = __SC_MEMLOCK_RANGE()

///|
pub let _sc_memory_protection : Int = __SC_MEMORY_PROTECTION()

///|
pub let _sc_message_passing : Int = __SC_MESSAGE_PASSING()

///|
pub let _sc_monotonic_clock : Int = __SC_MONOTONIC_CLOCK()

///|
pub let _sc_mq_open_max : Int = __SC_MQ_OPEN_MAX()

///|
pub let _sc_mq_prio_max : Int = __SC_MQ_PRIO_MAX()

///|
pub let _sc_ngroups_max : Int = __SC_NGROUPS_MAX()

///|
pub let _sc_open_max : Int = __SC_OPEN_MAX()

///|
pub let _sc_page_size : Int = __SC_PAGE_SIZE()

///|
pub let _sc_pagesize : Int = __SC_PAGESIZE()

///|
pub let _sc_prioritized_io : Int = __SC_PRIORITIZED_IO()

///|
pub let _sc_priority_scheduling : Int = __SC_PRIORITY_SCHEDULING()

///|
pub let _sc_raw_sockets : Int = __SC_RAW_SOCKETS()

///|
pub let _sc_re_dup_max : Int = __SC_RE_DUP_MAX()

///|
pub let _sc_reader_writer_locks : Int = __SC_READER_WRITER_LOCKS()

///|
pub let _sc_realtime_signals : Int = __SC_REALTIME_SIGNALS()

///|
pub let _sc_regexp : Int = __SC_REGEXP()

///|
pub let _sc_rtsig_max : Int = __SC_RTSIG_MAX()

///|
pub let _sc_saved_ids : Int = __SC_SAVED_IDS()

///|
pub let _sc_sem_nsems_max : Int = __SC_SEM_NSEMS_MAX()

///|
pub let _sc_sem_value_max : Int = __SC_SEM_VALUE_MAX()

///|
pub let _sc_semaphores : Int = __SC_SEMAPHORES()

///|
pub let _sc_shared_memory_objects : Int = __SC_SHARED_MEMORY_OBJECTS()

///|
pub let _sc_shell : Int = __SC_SHELL()

///|
pub let _sc_sigqueue_max : Int = __SC_SIGQUEUE_MAX()

///|
pub let _sc_spawn : Int = __SC_SPAWN()

///|
pub let _sc_spin_locks : Int = __SC_SPIN_LOCKS()

///|
pub let _sc_sporadic_server : Int = __SC_SPORADIC_SERVER()

///|
pub let _sc_ss_repl_max : Int = __SC_SS_REPL_MAX()

///|
pub let _sc_stream_max : Int = __SC_STREAM_MAX()

///|
pub let _sc_symloop_max : Int = __SC_SYMLOOP_MAX()

///|
pub let _sc_synchronized_io : Int = __SC_SYNCHRONIZED_IO()

///|
pub let _sc_thread_attr_stackaddr : Int = __SC_THREAD_ATTR_STACKADDR()

///|
pub let _sc_thread_attr_stacksize : Int = __SC_THREAD_ATTR_STACKSIZE()

///|
pub let _sc_thread_cputime : Int = __SC_THREAD_CPUTIME()

///|
pub let _sc_thread_destructor_iterations : Int = __SC_THREAD_DESTRUCTOR_ITERATIONS()

///|
pub let _sc_thread_keys_max : Int = __SC_THREAD_KEYS_MAX()

///|
pub let _sc_thread_prio_inherit : Int = __SC_THREAD_PRIO_INHERIT()

///|
pub let _sc_thread_prio_protect : Int = __SC_THREAD_PRIO_PROTECT()

///|
pub let _sc_thread_priority_scheduling : Int = __SC_THREAD_PRIORITY_SCHEDULING()

///|
pub let _sc_thread_process_shared : Int = __SC_THREAD_PROCESS_SHARED()

///|
pub let _sc_thread_robust_prio_inherit : Int = __SC_THREAD_ROBUST_PRIO_INHERIT()

///|
pub let _sc_thread_robust_prio_protect : Int = __SC_THREAD_ROBUST_PRIO_PROTECT()

///|
pub let _sc_thread_safe_functions : Int = __SC_THREAD_SAFE_FUNCTIONS()

///|
pub let _sc_thread_sporadic_server : Int = __SC_THREAD_SPORADIC_SERVER()

///|
pub let _sc_thread_stack_min : Int = __SC_THREAD_STACK_MIN()

///|
pub let _sc_thread_threads_max : Int = __SC_THREAD_THREADS_MAX()

///|
pub let _sc_threads : Int = __SC_THREADS()

///|
pub let _sc_timeouts : Int = __SC_TIMEOUTS()

///|
pub let _sc_timer_max : Int = __SC_TIMER_MAX()

///|
pub let _sc_timers : Int = __SC_TIMERS()

///|
pub let _sc_trace : Int = __SC_TRACE()

///|
pub let _sc_trace_event_filter : Int = __SC_TRACE_EVENT_FILTER()

///|
pub let _sc_trace_event_name_max : Int = __SC_TRACE_EVENT_NAME_MAX()

///|
pub let _sc_trace_inherit : Int = __SC_TRACE_INHERIT()

///|
pub let _sc_trace_log : Int = __SC_TRACE_LOG()

///|
pub let _sc_trace_name_max : Int = __SC_TRACE_NAME_MAX()

///|
pub let _sc_trace_sys_max : Int = __SC_TRACE_SYS_MAX()

///|
pub let _sc_trace_user_event_max : Int = __SC_TRACE_USER_EVENT_MAX()

///|
pub let _sc_tty_name_max : Int = __SC_TTY_NAME_MAX()

///|
pub let _sc_typed_memory_objects : Int = __SC_TYPED_MEMORY_OBJECTS()

///|
pub let _sc_tzname_max : Int = __SC_TZNAME_MAX()

///|
pub let _sc_v7_ilp32_off32 : Int = __SC_V7_ILP32_OFF32()

///|
pub let _sc_v7_ilp32_offbig : Int = __SC_V7_ILP32_OFFBIG()

///|
pub let _sc_v7_lp64_off64 : Int = __SC_V7_LP64_OFF64()

///|
pub let _sc_v7_lpbig_offbig : Int = __SC_V7_LPBIG_OFFBIG()

///|
pub let _sc_v6_ilp32_off32 : Int = __SC_V6_ILP32_OFF32()

///|
pub let _sc_v6_ilp32_offbig : Int = __SC_V6_ILP32_OFFBIG()

///|
pub let _sc_v6_lp64_off64 : Int = __SC_V6_LP64_OFF64()

///|
pub let _sc_v6_lpbig_offbig : Int = __SC_V6_LPBIG_OFFBIG()

///|
pub let _sc_version : Int = __SC_VERSION()

///|
pub let _sc_xopen_crypt : Int = __SC_XOPEN_CRYPT()

///|
pub let _sc_xopen_enh_i18n : Int = __SC_XOPEN_ENH_I18N()

///|
pub let _sc_xopen_realtime : Int = __SC_XOPEN_REALTIME()

///|
pub let _sc_xopen_realtime_threads : Int = __SC_XOPEN_REALTIME_THREADS()

///|
pub let _sc_xopen_shm : Int = __SC_XOPEN_SHM()

///|
pub let _sc_xopen_streams : Int = __SC_XOPEN_STREAMS()

///|
pub let _sc_xopen_unix : Int = __SC_XOPEN_UNIX()

///|
pub let _sc_xopen_version : Int = __SC_XOPEN_VERSION()

///|
pub let _cs_path : Int = __CS_PATH()

///|
pub let _cs_posix_v7_ilp32_off32_cflags : Int = __CS_POSIX_V7_ILP32_OFF32_CFLAGS()

///|
pub let _cs_posix_v7_ilp32_off32_ldflags : Int = __CS_POSIX_V7_ILP32_OFF32_LDFLAGS()

///|
pub let _cs_posix_v7_ilp32_off32_libs : Int = __CS_POSIX_V7_ILP32_OFF32_LIBS()

///|
pub let _cs_posix_v7_ilp32_offbig_cflags : Int = __CS_POSIX_V7_ILP32_OFFBIG_CFLAGS()

///|
pub let _cs_posix_v7_ilp32_offbig_ldflags : Int = __CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS()

///|
pub let _cs_posix_v7_ilp32_offbig_libs : Int = __CS_POSIX_V7_ILP32_OFFBIG_LIBS()

///|
pub let _cs_posix_v7_lp64_off64_cflags : Int = __CS_POSIX_V7_LP64_OFF64_CFLAGS()

///|
pub let _cs_posix_v7_lp64_off64_ldflags : Int = __CS_POSIX_V7_LP64_OFF64_LDFLAGS()

///|
pub let _cs_posix_v7_lp64_off64_libs : Int = __CS_POSIX_V7_LP64_OFF64_LIBS()

///|
pub let _cs_posix_v7_lpbig_offbig_cflags : Int = __CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS()

///|
pub let _cs_posix_v7_lpbig_offbig_ldflags : Int = __CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS()

///|
pub let _cs_posix_v7_lpbig_offbig_libs : Int = __CS_POSIX_V7_LPBIG_OFFBIG_LIBS()

///|
pub let _cs_posix_v7_width_restricted_envs : Int = __CS_POSIX_V7_WIDTH_RESTRICTED_ENVS()

///|
pub let _cs_v7_env : Int = __CS_V7_ENV()

///|
pub let _cs_posix_v6_ilp32_off32_cflags : Int = __CS_POSIX_V6_ILP32_OFF32_CFLAGS()

///|
pub let _cs_posix_v6_ilp32_off32_ldflags : Int = __CS_POSIX_V6_ILP32_OFF32_LDFLAGS()

///|
pub let _cs_posix_v6_ilp32_off32_libs : Int = __CS_POSIX_V6_ILP32_OFF32_LIBS()

///|
pub let _cs_posix_v6_ilp32_offbig_cflags : Int = __CS_POSIX_V6_ILP32_OFFBIG_CFLAGS()

///|
pub let _cs_posix_v6_ilp32_offbig_ldflags : Int = __CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS()

///|
pub let _cs_posix_v6_ilp32_offbig_libs : Int = __CS_POSIX_V6_ILP32_OFFBIG_LIBS()

///|
pub let _cs_posix_v6_lp64_off64_cflags : Int = __CS_POSIX_V6_LP64_OFF64_CFLAGS()

///|
pub let _cs_posix_v6_lp64_off64_ldflags : Int = __CS_POSIX_V6_LP64_OFF64_LDFLAGS()

///|
pub let _cs_posix_v6_lp64_off64_libs : Int = __CS_POSIX_V6_LP64_OFF64_LIBS()

///|
pub let _cs_posix_v6_lpbig_offbig_cflags : Int = __CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS()

///|
pub let _cs_posix_v6_lpbig_offbig_ldflags : Int = __CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS()

///|
pub let _cs_posix_v6_lpbig_offbig_libs : Int = __CS_POSIX_V6_LPBIG_OFFBIG_LIBS()

///|
pub let _cs_posix_v6_width_restricted_envs : Int = __CS_POSIX_V6_WIDTH_RESTRICTED_ENVS()

///|
pub let _cs_v6_env : Int = __CS_V6_ENV()
